services:
  postgres:
    image: postgres:16
    container_name: bharatpayops-postgres
    environment:
      POSTGRES_DB: bharatpayops
      POSTGRES_USER: bharatpayops_user
      POSTGRES_PASSWORD: bharatpayops_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: